import Head from 'next/head'
import Image from 'next/image'
import { Curriculum } from './Curriculum'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Job Coach App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        

        <div >
          <Curriculum />
        </div>
      </main>

      <footer >
        
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        
      </footer>
    </div>
  )
}
